matrix:
  - name: markdown
    pipeline:
      - pyspelling.filters.text:
      - pyspelling.filters.context:
          context_visible_first: true
          # Ignore YAML at the top of juptext-md file
          # (but may also exclude other content?)
          delimiters:
            - open: "(?s)^(?P<open> *-{3,})$"
              close: "^(?P=open)$"
      - pyspelling.filters.url:
      - pyspelling.filters.markdown:
          markdown_extensions:
            - pymdownx.superfences:
      - pyspelling.filters.html:
          comments: false
          ignores:
            - code
            - pre
            - tt
      - pyspelling.parsers.markdown_parser:
          markdown_extensions:
            - markdown.extensions.toc:
                slugify: !!python/name:pymdownx.slugs.uslugify
                permalink: "\ue157"
            - markdown.extensions.admonition
            - markdown.extensions.smarty
    source:
      - content/**/*.md
