baseURL = "https://priver.dev/"
author = "Emil Privér"
copyright = "Copyright © 2022–2022, Emil Privér; all rights reserved."
paginate = 5
languageCode = "en"
DefaultContentLanguage = "en"
ignoreErrors = ["error-remote-getjson"]
theme = "priver"
title = "Emil Privér"

enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true
pygmentsUseClasses = true

[minify]
  disableXML = true

[outputs]
  home = ["html", "rss", "json"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[languages.en]
  languageName = "English"
  weight = 1

  [languages.en.taxonomies]
    tag = "tags"
    series = "series"
    recipes = "recipes"

[[languages.en.menu.main]]
  name = "Archive"
  url = "blog"
  weight = 5

[[languages.en.menu.main]]
  name = "Search"
  url = "search/"
  weight = 10

[[languages.en.menu.main]]
  name = "Tags"
  url = "tags/"
  weight = 10

[[languages.en.menu.main]]
  name = "Twitter"
  url = "https://x.com/emil_priver"

[[languages.en.menu.main]]
  name = "Github"
  url = "https://github.com/emilpriver"

[privacy]
  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]
  [services.instagram]
    disableInlineCSS = true
  [services.twitter]
    disableInlineCSS = true


[imaging]
  anchor = 'Smart'
  bgColor = '#ffffff'
  hint = 'photo'
  quality = 20
  resampleFilter = 'Box'

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[params]
  defaulttheme = true
  ShowShareButtons = true
  ShowReadingTime = true
  displayFullLangName = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowRssButtonInSectionTermList = true
  ShowToc = true

  [params.homeInfoParams]
    Title = "Emil Privér"
    Content = "Hey! My name is Emil Privér, I write about stuffs I learn and build. I am a software developer who likes exploring stuffs. Sometimes I like to write and then I post it here"

  [params.social]
    twitter= "https://twitter.com/emil_priver"
    github= "https://github.com/emilpriver"
    linkedin= "https://www.linkedin.com/in/emilpriver"

  [params.editPost]
    URL = "https://github.com/emilpriver/go-hugo-portfolio/tree/main/content"
    Text =  "Suggest Changes"
    appendFilePath = true

  [params.assets]
    disableHLJS = true

[security]
  [security.funcs]
    getenv = ["^VERCEL_", "^HUGO_"]
